baseURL = "https://dahouzi.cn"
languageCode = "zh-CN"
title = "大猴子"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X/G-XXXXXXXXXX
defaultContentLanguage = "zh-hans"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "空空"



[params]
  author = "空空"
  subtitle = "You can be just the one you wanna be！"
  keywords = "旅行,读书,零代码,临终关怀,职业规划,生涯规划"
  description = "没有专注领域，只为探索自己"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "粤ICP备14083194号"

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 配置 waline 评论系统,教程参考 https://waline.js.org/
[params.waline]
  enable = true
  placeholder = "说点什么吧..."
  serverURL = "comment.dahouzi.cn" #换成你的serverURL
## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
